[[collection]]
type = "card"
icon = "/img/language.png"
title = "StarPlat MLIR"
subtitle = "AI Researcher"
date = "2025 Jan - Present"
content = """\
Work on the DeepSeek project, a research project that aims to develop a new generation of AI models that can understand and generate natural language text.

The project is focused on developing models that can generate text that is coherent, informative, and engaging, and that can be used in a wide range of applications, including chatbots, virtual assistants, and content generation tools.
"""

[[collection]]
type = "card"
icon = "/img/semiconductor.png"
title = "OpenAI"
subtitle = "Machine Learning Engineer"
date = "2021-2025"
content = """\
Alone with the team, I worked on developing new machine learning models and algorithms for a wide range of applications, including natural language processing, computer vision, and reinforcement learning. I also worked on developing new tools and frameworks for training and deploying machine learning models, and on building systems that can scale to handle large amounts of data and compute resources.
"""

[[collection]]
type = "card"
icon = "/img/gear.png"
title = "AutoRegex"
subtitle = "A Regex Engine Inspired by the Dragon Book"
date = "Sep 2023 - Oct 2023"
content = """\
A Regex engine that converts regular expressions into deterministic finite automata (DFA) and uses the resulting DFA to match patterns. The algorithm employed in this conversion is based on the well-known "Dragon Book" (Compilers Principles, Techniques and Tool by ALSU).
"""