[[collection]]
type = "art"
img = "/img/ms_seminar.png"
title = "Task-Based MLIR Compilation for HPC Clusters"
link = "https://www.canva.com/design/DAHBFupIqcY/AFn6wUVn0x6LTpnfSxaVeg/edit?utm_content=DAHBFupIqcY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton"
subtitle = "MS Seminar"
content = "This seminar presents a compiler framework for distributed heterogeneous HPC systems built using MLIR. The work explores task-based decomposition of workloads and compilation strategies that map computations efficiently across CPUs and GPUs in cluster environments. It discusses the design of intermediate representations, scheduling strategies, and runtime integration for scalable execution on multi-node systems."

[[collection]]
type = "art"
img = "/img/iisc_poster.png"
title = "An IR for Distributed Heterogeneous Computing"
link = "https://events.csa.iisc.ac.in/csworkshop2025/"
subtitle = "Computer Systems Workshop 2025"
content = "This work introduces DHIR, an MLIR-based intermediate representation designed to unify distributed and heterogeneous execution. DHIR enables task parallelism, device placement, and communication within a single abstraction, improving programmability and compiler optimization across CPUs, GPUs, and clusters."

[[collection]]
type = "art"
img = "/img/pldi_src.png"
title = "An IR for Distributed Heterogeneous Computing"
link = "https://pldi25.sigplan.org/track/pldi-2025-src"
subtitle = "PLDI SRC 2025"
content = "This work introduces DHIR, an MLIR-based intermediate representation designed to unify distributed and heterogeneous execution. DHIR enables task parallelism, device placement, and communication within a single abstraction, improving programmability and compiler optimization across CPUs, GPUs, and clusters."

